name = "Test 2 Pack"
author = "Freddie_06"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10d6049c48707ead4b0d7a0d004d6d30c40a0cc5b97789d6b42dcf69ebf89cdd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
