name = "Test 2 Pack"
author = "Freddie_06"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dcc9e992a0b78a15900e08a5117412bc65b05a8c620d82a3b868491d95245bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
