name = "Test 2 Pack"
author = "Freddie_06"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88a702b792c73b757385ffdca3367ab9648f4e33fd94b92a3e7ac45ed9f14f82"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
